# Site Settings
title: "Chicago BIPOC Birders"
description: "A grassroots effort to build community among BIPOC birders of Chicago."
url: "https://windycitybirdlab.github.io"
baseurl: "/chicagobipocbirders"

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Collections
collections_dir: collections

# Exclude files from build
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - README.md