name: "Chicago BIPOC Birders"
avatar_image: "/assets/images/chicagobipocbirderslogo.png"
description: "A grassroots effort to build community among BIPOC birders of Chicago."

links:
  - url: "https://docs.google.com/forms/d/e/1FAIpQLSfFVIfDskadduzcwoNFyALhLByko7gbu_u5lZN8PBfvkODP8w/viewform?usp=sf_link"
    title: "Slack"
    text: "Chat with your fellow Chicago BIPOC birders about bird sightings, ID, or upcoming events"
  
  - url: "https://mailbob.io/u/chicagobipocbirders/"
    title: "Newsletter"
    text: "Subscribe to our Newsletter"
  
  - url: "https://calendar.google.com/calendar/u/0/render?cid=bipocbirderschicago%40gmail.com"
    title: "Calendar"
    text: "Take a look at our birding Calendar"
  
  - url: "https://instagram.com/chicago.bipoc.birders?igshid=MWdkeG8wZWc3MDZnZQ=="
    title: "Instagram"
    text: "Follow our new instagram @chicago.bipoc.birders"
  
  - url: "https://www.eventbrite.com/o/chicago-bipoc-birders-47305888343"
    title: "Eventbrite"
    text: "Follow us on Eventbrite to get notified about upcoming birding events."

social:
  email: "bipocbirderschicago@gmail.com"
  instagram: "https://instagram.com/chicago.bipoc.birders"

contact:
  email: "bipocbirderschicago@gmail.com"